language: ruby
cache: bundler
bundler_args: --without integration development
before_script: bundle exec berks
script:
  - bundle exec foodcritic -f any -t ~FC001 -t ~FC007 -t ~FC023 .
  - bundle exec rubocop
  - bundle exec rspec test/integration/default/serverspec/
  